name: Commit and push to repository

on:
  workflow_dispatch: 

jobs:
  commit-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit and Push
        run: |
          echo "New commit" >> newfile.txt
          git add newfile.txt
          git commit -m "Add newfile.txt"
          git push origin main
            